spring.application.name=openemr_project
server.port=8081

# MySQL Ba?lant? Ayarlar?
spring.datasource.url=jdbc:mysql://localhost:3333/openemr?useUnicode=true&characterEncoding=UTF-8
spring.datasource.password=root
spring.datasource.username=root

# Hibernate Ayarlar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# OpenEMR integration
openemr.base-url=http://localhost:8080
openemr.client-id=pIzEbhhgE_hAdG8U-dpKRCq-Mnz6NF7Qh0ZhK_r1Y5k
openemr.client-secret=QhDFO3s_fue05DFfgoHTapOEaXnXZsNiMbQbTLHURcVuBKZDv_TDvZZeJXr1AFeeckpO8pvpQA9duLH_DpO6SQ
openemr.username=admin
openemr.password=admin
openemr.user-role=users
openemr.scope=api:oemr user/patient.write user/appointment.write
openemr.appointment-category-id=10
openemr.appointment-title=Checkup
openemr.appointment-status=-
openemr.appointment-facility-id=3
openemr.appointment-billing-location-id=3
openemr.appointment-provider-id=1