spring.application.name=openemr_project

# MySQL Ba?lant? Ayarlar?
spring.datasource.url=jdbc:mysql://localhost:3333/openemr?useUnicode=true&characterEncoding=UTF-8
spring.datasource.password=123456
spring.datasource.username=root

# Hibernate Ayarlar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true